# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gtelwifi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gtelwifi/proprietary//bin/calibration_init:system//bin/calibration_init \
    vendor/samsung/gtelwifi/proprietary//bin/ext_data.sh:system//bin/ext_data.sh \
    vendor/samsung/gtelwifi/proprietary//bin/ext_kill.sh:system//bin/ext_kill.sh \
    vendor/samsung/gtelwifi/proprietary//bin/ext_symlink.sh:system//bin/ext_symlink.sh \
    vendor/samsung/gtelwifi/proprietary//bin/inputfreq.sh:system//bin/inputfreq.sh \
    vendor/samsung/gtelwifi/proprietary//bin/prepare_param.sh:system//bin/prepare_param.sh \
    vendor/samsung/gtelwifi/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/gtelwifi/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/gtelwifi/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/gtelwifi/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/gtelwifi/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/gtelwifi/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/gtelwifi/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/gtelwifi/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/audio.primary.sc8830.so:system/lib/hw/audio.primary.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/audio_policy.sc8830.so:system/lib/hw/audio_policy.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/gralloc.sc8830.so:system/lib/hw/gralloc.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/hwcomposer.sc8830.so:system/lib/hw/hwcomposer.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/hw/sprd_gsp.sc8830.so:system/lib/hw/sprd_gsp.sc8830.so \
    vendor/samsung/gtelwifi/proprietary/lib/lib_SamsungRec_V03010.so:system/lib/lib_SamsungRec_V03010.so \
    vendor/samsung/gtelwifi/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/gtelwifi/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/gtelwifi/proprietary/lib/libaudiopolicy_sec.so:system/lib/libaudiopolicy_sec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libbinder.so:system/lib/libbinder.so \
    vendor/samsung/gtelwifi/proprietary/lib/libcontrolcsc.so:system/lib/libcontrolcsc.so \
    vendor/samsung/gtelwifi/proprietary/lib/libdumpdata.so:system/lib/libdumpdata.so \
    vendor/samsung/gtelwifi/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/samsung/gtelwifi/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/gtelwifi/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/gtelwifi/proprietary/lib/libnvexchange.so:system/lib/libnvexchange.so \
    vendor/samsung/gtelwifi/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/gtelwifi/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/gtelwifi/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/gtelwifi/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/gtelwifi/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/gtelwifi/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_aacdec.so:system/lib/libstagefright_sprd_aacdec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_h264dec.so:system/lib/libstagefright_sprd_h264dec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_h264enc.so:system/lib/libstagefright_sprd_h264enc.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_mp3dec.so:system/lib/libstagefright_sprd_mp3dec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_mpeg4dec.so:system/lib/libstagefright_sprd_mpeg4dec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_mpeg4enc.so:system/lib/libstagefright_sprd_mpeg4enc.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_soft_h264dec.so:system/lib/libstagefright_sprd_soft_h264dec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_soft_mpeg4dec.so:system/lib/libstagefright_sprd_soft_mpeg4dec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefright_sprd_vpxdec.so:system/lib/libstagefright_sprd_vpxdec.so \
    vendor/samsung/gtelwifi/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/samsung/gtelwifi/proprietary/lib/libtinyalsa.so:system/lib/libtinyalsa.so \
    vendor/samsung/gtelwifi/proprietary/lib/libuvdenoise.so:system/lib/libuvdenoise.so \
    vendor/samsung/gtelwifi/proprietary/lib/libvbeffect.so:system/lib/libvbeffect.so \
    vendor/samsung/gtelwifi/proprietary/lib/libvbpga.so:system/lib/libvbpga.so \
    vendor/samsung/gtelwifi/proprietary/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd:system/vendor/firmware/BCM43430A1_001.002.009.0022.0000_Samsung_TabE_SM-T561_TEST_ONLY.hcd \
    vendor/samsung/gtelwifi/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/gtelwifi/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/gtelwifi/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so

PRODUCT_PACKAGES += \
    libatchannel
